export const FOREX_PAIRS = [
    'EURUSD',
    'GBPUSD',
    'USDJPY',
    'AUDUSD',
    'USDCAD',
    'USDCHF',
    'EURGBP',
    'EURJPY',
    'GBPJPY',
    'NZDUSD',
    'USDMXN',
    'EURAUD',
    'EURCHF',
    'GBPAUD',
    'GBPCAD',
    'GBPCHF',
    'AUDCAD',
    'AUDCHF',
    'AUDJPY',
    'CHFJPY',
    'EURNZD',
    'EURCAD',
    'AUDNZD',
    'CADJPY',
    'NZDJPY',
    'USDSEK',
] as const;

export const CRYPTO_PAIRS = [
    'BTCUSD',
    'ETHUSD',
    'XRPUSD',
    'DOTUSD',
    'ADAUSD',
    'SOLUSD',
    'BNBUSD',
    'DOGEUSD',
    'MATICUSD',
    'AVAXUSD',
    'LINKUSD',
    'UNIUSD',
    'ATOMUSD',
    'LTCUSD',
    'FILUSD',
    'TRXUSD',
    'XLMUSD',
    'EOSUSD',
    'XTZUSD',
    'ALGOUSD',
    'NEARUSD',
    'ICPUSD',
    'AAVEUSD',
    'FTMUSD',
    'SANDUSD',
    'MANAUSD',
] as const;
