export const FOREX_PAIRS = ['USDJPY', 'GBPUSD', 'AUDUSD', 'EURUSD', 'USDCAD', 'USDCHF', 'NZDUSD', 'GBPAUD', 'GBPCAD', 'GBPNZD', 'EURJPY'] as const;

export const CRYPTO_PAIRS = ['BTCUSD', 'ETHUSD', 'LTCUSD', 'BCHUSD', 'PAXGUSD', 'LINKUSD', 'UNIUSD', 'AAVEUSD'] as const;
